services:
  db:
    image: postgres:15
    container_name: bd2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sofisticada
      POSTGRES_DB: streamers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bd2_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      PG_CONX: postgresql://postgres:sofisticada@db:5432/streamers

volumes:
  postgres_data: