services:
  db:
    image: postgres:15
    container_name: bd2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sofisticada
      POSTGRES_DB: streamers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: python:3.12
    container_name: bd2_app
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    command: tail -f /dev/null  # mant√©m o container ativo

volumes:
  postgres_data: