services:
  db:
    image: postgres:15
    container_name: bd2_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sofisticada
      POSTGRES_DB: streamers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
